# Generated by Django 4.0.4 on 2022-05-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_id', models.IntegerField()),
                ('investment_id', models.IntegerField()),
                ('fees_amount', models.IntegerField()),
                ('date_added', models.DateField()),
                ('fees_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cashcall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('IBAN', models.IntegerField()),
                ('email_send', models.CharField(max_length=255)),
                ('date_added', models.DateField()),
                ('invoice_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_created=True)),
                ('investor_id', models.IntegerField()),
                ('startup_name', models.CharField(max_length=255)),
                ('invested_amount', models.IntegerField()),
                ('percentage_fees', models.IntegerField()),
                ('fees_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('credit', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
