# Generated by Django 4.0.4 on 2022-05-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneRagTime_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashcall',
            name='IBAN',
            field=models.CharField(max_length=255),
        ),
    ]
